#!/bin/bash

YELLOW='\033[1;33m' #YELLOW color
NC='\033[0m' # No Color

usage() {
	echo -e "To create default configuration, run, ./build_script -defconfig"
	echo -e "To build the kernel, dtb, and tar file, run,  ./build_script -build"
	echo -e "To clean the object files and configurations, run, ./build_script -distclean"
	echo -e "To open the kernel drivers config (make menuconfig), run, ./build_script -config"
	exit 0
}

if [[ ( $1 == "-help") || ( $1 == "-h") ]]
	then
	echo -e "./build_script\nThis script is used to configure the kernel & for build purpose"
	usage
fi	

if [[ ( $1 == "-defconfig") ]]
	then
	make distclean ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-
	make nitrogen6x_leonardo_defconfig ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-
	exit 0
fi

if [[ ( $1 == "-distclean") ]]
	then
	make distclean ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-
	exit 0
fi

if [[ ( $1 == "-clean") ]]
	then
	make clean ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-
	exit 0
fi

if [[ ( $1 == "-config") ]]
	then
	make menuconfig ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-
	exit 0
fi


if [[ ( $1 == "-build") ]]
	then
	make zImage modules dtbs -j4 ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-
	echo -e "${YELLOW} Kernel build done! ${NC}"
	make -C ubuntunize tarball ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-
	echo -e "${YELLOW} Tar done! ${NC}"
	cp -rf ubuntunize/*.tar.gz /home/titus/
	echo -e "${YELLOW} Copy done! ${NC}"
#	scp -r /home/titus/linux-3.14.52-svn160.tar.gz  ubuntu@10.100.1.35:/home/ubuntu
#	echo -e "${YELLOW} SSH copy done! ${NC}"
	exit 0
fi

usage
